// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpotifyChart.WebAPI;

namespace SpotifyChart.WebAPI.Migrations
{
    [DbContext(typeof(SpotifyChartDbContext))]
    [Migration("20190416153051_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Tasprof.Components.SpotifyChart.Models.SpotifyChart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("SpotifyCharts");
                });

            modelBuilder.Entity("Tasprof.Components.SpotifyChart.Models.SpotifyChartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Artist");

                    b.Property<int>("ChartId");

                    b.Property<DateTime>("Created");

                    b.Property<int>("Position");

                    b.Property<string>("Title");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("ChartId");

                    b.ToTable("SpotifyChartItems");
                });

            modelBuilder.Entity("Tasprof.Components.SpotifyChart.Models.SpotifyChartItem", b =>
                {
                    b.HasOne("Tasprof.Components.SpotifyChart.Models.SpotifyChart", "Chart")
                        .WithMany("Items")
                        .HasForeignKey("ChartId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
